In [1]:
import get_statements
import pandas as pd
import yfinance as yf
import financial_line_items

In [2]:
porto = ['nvda', 'aapl', 'ionq', 'rgti', 'goog']

In [3]:
nvda_quarterly = get_statements.tickers_quarterly_statements('nvda')

In [4]:
type(nvda_quarterly)

dict

In [5]:
portfolio = get_statements.tickers_statements(porto)

In [24]:
line_ass = {x:portfolio[x]['balance_sheet'].loc['Total Assets'] for x in portfolio.keys()}

In [7]:
portfolio_quarterly = get_statements.tickers_quarterly_statements(porto)

In [10]:
portfolio_quart_income = get_statements.tickers_quarterly_income_statements(portfolio_quarterly)

In [11]:
portfolio_quarterly['AAPL']['quarterly_income_statement']

,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0,NaN,NaN
Tax Rate For Calcs,0.21,0.21,0.159,0.158,0.21,NaN,NaN
Normalized EBITDA,45912000000.0,32502000000.0,28202000000.0,30736000000.0,43221000000.0,NaN,NaN
Net Income From Continuing Operation Net Minority Interest,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Reconciled Depreciation,3080000000.0,2911000000.0,2850000000.0,2836000000.0,2848000000.0,NaN,NaN
Reconciled Cost Of Revenue,66025000000.0,51051000000.0,46099000000.0,48482000000.0,64720000000.0,NaN,NaN
EBITDA,45912000000.0,32502000000.0,28202000000.0,30736000000.0,43221000000.0,NaN,NaN
EBIT,42832000000.0,29591000000.0,25352000000.0,27900000000.0,40373000000.0,NaN,NaN
Net Interest Income,NaN,NaN,NaN,NaN,NaN,-18000000.0,-18000000.0
Interest Expense,NaN,NaN,NaN,NaN,NaN,1002000000.0,998000000.0
Interest Income,NaN,NaN,NaN,NaN,NaN,984000000.0,980000000.0
Normalized Income,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Net Income From Continuing And Discontinued Operation,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Total Expenses,81468000000.0,65339000000.0,60425000000.0,62853000000.0,79202000000.0,NaN,NaN
Total Operating Income As Reported,42832000000.0,29591000000.0,25352000000.0,27900000000.0,40373000000.0,NaN,NaN
Diluted Average Shares,15150865000.0,15242853000.0,15348175000.0,15464709000.0,15576641000.0,NaN,NaN
Basic Average Shares,15081724000.0,15171990000.0,15287521000.0,15405856000.0,15509763000.0,NaN,NaN
Diluted EPS,2.4,0.97,1.4,1.53,2.18,NaN,NaN
Basic EPS,2.41,0.97,1.4,1.53,2.19,NaN,NaN
Diluted NI Availto Com Stockholders,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Net Income Common Stockholders,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Net Income,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Net Income Including Noncontrolling Interests,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Net Income Continuous Operations,36330000000.0,14736000000.0,21448000000.0,23636000000.0,33916000000.0,NaN,NaN
Tax Provision,6254000000.0,14874000000.0,4046000000.0,4422000000.0,6407000000.0,NaN,NaN
Pretax Income,42584000000.0,29610000000.0,25494000000.0,28058000000.0,40323000000.0,NaN,NaN
Other Income Expense,-248000000.0,19000000.0,142000000.0,158000000.0,-50000000.0,NaN,NaN
Other Non Operating Income Expenses,-248000000.0,19000000.0,142000000.0,158000000.0,-50000000.0,NaN,NaN
Net Non Operating Interest Income Expense,NaN,NaN,NaN,NaN,NaN,-18000000.0,-18000000.0
Interest Expense Non Operating,NaN,NaN,NaN,NaN,NaN,1002000000.0,998000000.0
Interest Income Non Operating,NaN,NaN,NaN,NaN,NaN,984000000.0,980000000.0
Operating Income,42832000000.0,29591000000.0,25352000000.0,27900000000.0,40373000000.0,NaN,NaN
Operating Expense,15443000000.0,14288000000.0,14326000000.0,14371000000.0,14482000000.0,NaN,NaN
Research And Development,8268000000.0,7765000000.0,8006000000.0,7903000000.0,7696000000.0,NaN,NaN
Selling General And Administration,7175000000.0,6523000000.0,6320000000.0,6468000000.0,6786000000.0,NaN,NaN
Gross Profit,58275000000.0,43879000000.0,39678000000.0,42271000000.0,54855000000.0,NaN,NaN
Cost Of Revenue,66025000000.0,51051000000.0,46099000000.0,48482000000.0,64720000000.0,NaN,NaN
Total Revenue,124300000000.0,94930000000.0,85777000000.0,90753000000.0,119575000000.0,NaN,NaN
Operating Revenue,124300000000.0,94930000000.0,85777000000.0,90753000000.0,119575000000.0,NaN,NaN

'Total Assets'

In [18]:
for x in portfolio_bs.keys(): pd.DataFrame(portfolio_bs[x])

In [10]:
'quarterly_income_statement' == 'quarterly_income_statement'

True

In [25]:
line_ass

{'NVDA': 2024-01-31    65728000000.0
 2023-01-31    41182000000.0
 2022-01-31    44187000000.0
 2021-01-31    28791000000.0
 Name: Total Assets, dtype: object,
 'AAPL': 2024-09-30    364980000000.0
 2023-09-30    352583000000.0
 2022-09-30    352755000000.0
 2021-09-30    351002000000.0
 2020-09-30               NaN
 Name: Total Assets, dtype: object,
 'IONQ': 2023-12-31    553580000.0
 2022-12-31    597992000.0
 2021-12-31    642028000.0
 2020-12-31     60478000.0
 Name: Total Assets, dtype: object,
 'RGTI': 2023-12-31    159913000.0
 2022-12-31    203442000.0
 2021-01-31     49682089.0
 Name: Total Assets, dtype: object,
 'GOOG': 2024-12-31    450256000000.0
 2023-12-31    402392000000.0
 2022-12-31    365264000000.0
 2021-12-31    359268000000.0
 2020-12-31               NaN
 Name: Total Assets, dtype: object}

In [42]:
def tickers_quarterly_income_statements(tickers_quarterly_statements):
    """Extract quarterly income statements from fetched data."""
    return {
    ticker:data['quarterly_income_statement'] 
    for ticker, data tickers_quarterly_statements.items()
}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3976337405.py, line 5)